name: selenium-python

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install selenium
        pip install allure
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - uses: actions/checkout@v4
      if: success() || failure()
    - run: |
        python -m pytest runner.py --alluredir ./results
        
        
    -name: set output
    if: success() || failure()
    id: results
    run: echo "artifactPath=./results" >> $GITHUB_OUTPUT

    -uses: actions/upload-artifacts@v4
     if: success() || failure()
     with:
        name: test-report
        path: ${{steps.results.outputs.artifactPath}}
